image: node:alpine

# Cache node modules - speeds up future builds
cache:
  paths:
  - node_modules

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - npm run export
  artifacts:
    paths:
    - out
  only:
    - master
